[feat] Character 생성/수정 API 구현
TeamCatchMe/Server pull request #19
Opened 2023-01-21 06:25 UTC by realwhyjay

## ✨ Pull Request
[feat] Character 생성/수정 API 구현

<br>

## 📦 Summary
- Closes #16 

<br>

## ✔️ Changed
- Character module, controller, service, test 파일 생성
- 캐츄 생성, 캐츄 수정 API 구현
- 캐츄 생성, 캐츄 수정 test
- Character 관련 DTO 구현

2023-01-21 15:36 UTC, devkwonsehoon requested changes
Good!

2023-01-21 15:36 UTC, devkwonsehoon commented on prisma/schema.prisma
> +  user_id    Int
근데 우리가 놓치고 있는게, id 값들을 int 로 하면 정말 서비스 규모가 커졌을 경우에
오버플로우가 날수도있어서 서비스 장애로 이어질 수 있다는 점..

그래서 우리 인덱스 관련은 bigint로 처리하는 것은 어떨까?

2023-01-21 15:36 UTC, devkwonsehoon commented on src/modules/v1/character/dto/character.dto.ts
> +  @MaxLength(20, { message: '닉네임은 1자 이상 20자 이하이여야 합니다' })
여기 닉네임 말고 캐츄 이름으로 해야할 듯 합니다!

```suggestion
  @MinLength(1, { message: '캐츄의 이름은 1자 이상 20자 이하이여야 합니다' })
  @MaxLength(20, { message: '캐츄의 이름은 1자 이상 20자 이하이여야 합니다' })
```

2023-01-21 15:36 UTC, devkwonsehoon commented on src/modules/v1/character/interfaces/character-repository.interface.ts
> +  ): Promise<Character>;
마찬가지로 인터페이스 내부에서도 바로 디비 모델에 접근하는것보다
그냥 순수 객체 하나 만들어서 써야할듯!

2023-01-21 15:36 UTC, devkwonsehoon commented on src/modules/v1/v1.module.ts
> +  imports: [...Modules, RouterModule.register(ModulesForVersioning), CharacterModule],
Modules 배열 안에다가 넣어주기만 하면 됩니다!!!!

URI 버저닝 한번에 돌려버릴려구 이렇게 해둔건데, 나중에 더 괜찮은 방식있으면 수정해봅시다

2023-01-21 15:36 UTC, devkwonsehoon commented on src/modules/v1/character/dto/character.dto.ts
> +  @IsNumber()
캐츄 종류는 정해져있으니까 요거를 range로 제한을 걸어둔다거나,
아니면.. 캐츄 타입을 enum으로 따로 관리해서 뭔가 타이핑을 해두는 것은 어떨까요?

2023-01-21 17:33 UTC, realwhyjay commented on prisma/schema.prisma
> +  user_id    Int
오키오키 좋아! 그럼 내가 이거 머지하기 전에 바꿔둘게!

2023-01-21 17:36 UTC, realwhyjay commented on src/modules/v1/v1.module.ts
> +  imports: [...Modules, RouterModule.register(ModulesForVersioning), CharacterModule],
아 이거는 cli로 모듈 생성하면서 저렇게 들어간거같음! 수정해둘게

2023-01-21 17:37 UTC, realwhyjay commented on src/modules/v1/character/dto/character.dto.ts
> +  @IsNumber()
이거 아무래도 그런식으로 하려고 했는데, 피그마에서 지금까지 나온 캐츄 타입 수를 찾지를 못해서 우선은 저렇게 넣어놨음다!
그거 확인되면 이후 작업하면서 수정해둘게!

2023-01-21 19:11 UTC, realwhyjay commented on prisma/schema.prisma
> +  user_id    Int
이거 바꿔서 작업하려 했는데 인덱스 관련 칼럼 타입을 다 bigint로 바꾸니까 생기는 문제가, 
Bigint는 JSON 형태로 serialize가 안되더라고.
그래서 id 값으로 JWT 토큰을 생성하면 에러가 남!
이걸 해결해주려면 매번 해당 bigint 값을 변환해줘야하는데, 이게 좀 번거로운 것 같아서 우선은 그대로 int로 남겨둔 상황!

또 생각해보면 db에서 int 타입이면 거의 21억정도까지는 커버 가능하니까, 오버플로우가 날 가능성이 적지 않을것 같아서
그냥 int로 그대로 써도 되지 않을까 싶기도 하구

2023-01-21 19:16 UTC, realwhyjay commented on src/modules/v1/character/interfaces/character-repository.interface.ts
> +  ): Promise<Character>;
순수 객체를 만든다는게 걍 디비 모델 말고 자체적으로 만든 모델 객체같은걸 하나 만들어서 써야한다는 의미인가??
그럼 그 character.dto 가져다가 쓰면 되려나???

내가 의미를 잘 이해를 못하겠어서, 만약 위에 내가 말한게 아니면 나중에 너가 작업한거 보고 참고해서 수정해볼게!

2023-01-23 02:37 UTC, devkwonsehoon commented on prisma/schema.prisma
> +  user_id    Int
맞네맞네 ㅋㅋ bigint 굳이 안해도 되겠다 낭비일듯!! int로 고고합시다

2023-01-23 02:38 UTC, devkwonsehoon commented on src/modules/v1/character/interfaces/character-repository.interface.ts
> +  ): Promise<Character>;
오키오키 내가 작업해서 올려둘게!!

2023-01-23 02:38 UTC, devkwonsehoon commented on src/modules/v1/v1.module.ts
> +  imports: [...Modules, RouterModule.register(ModulesForVersioning), CharacterModule],
good!

2023-01-23 02:38 UTC, devkwonsehoon commented on src/modules/v1/character/dto/character.dto.ts
> +  @IsNumber()
네넵!

2023-01-24 05:50 UTC, merged