[fix] 둘러보기 조회시 캐릭터 정렬 안되는 문제 해결
TeamCatchMe/Server pull request #40
Opened 2023-04-03 15:58 UTC by realwhyjay

## 📦 Summary
- 둘러보기 조회시 캐릭터 정렬 안되는 문제 해결

<br>

## ✔️ Changed
- 왜인지 prisma 쿼리 단에서 정렬이 되지 않아 코드로 해결함

2023-04-04 03:51 UTC, devkwonsehoon requested changes
캐릭터 정렬에 대한 쿼리가 원래 없지 않아!?

지금은 Activity 내에서 date로 desc 정렬하고 있어서 그런거 같은데
한번 확인해주실 수 있을랑가??

2023-04-04 03:51 UTC, devkwonsehoon commented on src/modules/v1/character/character.repository.ts
> +    const result = sortedCharacters
lodash 사용해보는 건 어뗘?! 
lodash 에서 제공하는건 시간복잡도가 어떨진 모르겠는데, 자스 기본 sort메서드가 합병정렬이라 또 괜찮을 것 같긴함니다.
그렇다면 sort만 따로 util로 빼는?

2023-04-04 08:18 UTC, realwhyjay commented
> 캐릭터 정렬에 대한 쿼리가 원래 없지 않아!?
> 
> 지금은 Activity 내에서 date로 desc 정렬하고 있어서 그런거 같은데 한번 확인해주실 수 있을랑가??

원래는 그냥 해당 쿼리에서 캐릭터를 Activity의 date를 기준으로 정렬해주려고 했었는데, 왜인지 prisma가 Character-Activity의 관계를 완전히 인식을 못하는것 같더라고. 나도 Activity 내에서 date로 desc 정렬하는 부분이 문제가 되나 싶어서 해당 부분 빼고 조회 해봤는데 Character의 값들을 Activity의 date를 기준으로 정렬하려하니 여전히 메소드에서 Activity의 date 값을 인식을 못하고 적용이 안되길래, 우선 빠르게 처리하려고 코드단으로 정렬 작업을 뺀 거였음!

2023-04-04 14:49 UTC, devkwonsehoon commented
> > 캐릭터 정렬에 대한 쿼리가 원래 없지 않아!?
> > 지금은 Activity 내에서 date로 desc 정렬하고 있어서 그런거 같은데 한번 확인해주실 수 있을랑가??
> 
> 원래는 그냥 해당 쿼리에서 캐릭터를 Activity의 date를 기준으로 정렬해주려고 했었는데, 왜인지 prisma가 Character-Activity의 관계를 완전히 인식을 못하는것 같더라고. 나도 Activity 내에서 date로 desc 정렬하는 부분이 문제가 되나 싶어서 해당 부분 빼고 조회 해봤는데 Character의 값들을 Activity의 date를 기준으로 정렬하려하니 여전히 메소드에서 Activity의 date 값을 인식을 못하고 적용이 안되길래, 우선 빠르게 처리하려고 코드단으로 정렬 작업을 뺀 거였음!

이런식으로 한번 해보는건어때?
const result = await prisma.character.findMany({
  orderBy: {
    Activity: {
      ascending: true // 특정 컬럼 머시꺵이
    }
  },
  where: {
    // 조건 설정
  },
  include: {
    Activity: true 
  }
})

2023-04-08 08:59 UTC, realwhyjay commented
> > > 캐릭터 정렬에 대한 쿼리가 원래 없지 않아!?
> > > 지금은 Activity 내에서 date로 desc 정렬하고 있어서 그런거 같은데 한번 확인해주실 수 있을랑가??
> > 
> > 
> > 원래는 그냥 해당 쿼리에서 캐릭터를 Activity의 date를 기준으로 정렬해주려고 했었는데, 왜인지 prisma가 Character-Activity의 관계를 완전히 인식을 못하는것 같더라고. 나도 Activity 내에서 date로 desc 정렬하는 부분이 문제가 되나 싶어서 해당 부분 빼고 조회 해봤는데 Character의 값들을 Activity의 date를 기준으로 정렬하려하니 여전히 메소드에서 Activity의 date 값을 인식을 못하고 적용이 안되길래, 우선 빠르게 처리하려고 코드단으로 정렬 작업을 뺀 거였음!
> 
> 이런식으로 한번 해보는건어때?
> 
> ```js
> const result = await prisma.character.findMany({
>   orderBy: {
>     Activity: {
>       ascending: true // 특정 컬럼 머시꺵이
>     }
>   },
>   where: {
>     // 조건 설정
>   },
>   include: {
>     Activity: true 
>   }
> })
> ```

비슷하게 했었는데 동작을 안해서 저렇게 코드단으로 넘겨버린 거였으 ㅠ

https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#sort-by-relation
내가 참조했던 prsima 문서인데, 저 방식을 그대로 적용해보니
<img width="548" alt="screenshot" src="https://user-images.githubusercontent.com/49263163/230712656-3f036d07-e4ea-419e-91d0-1d6f5ec8f765.png">
Activity의 data 프로퍼티를 읽지를 못하더라고.
그래서 prisma client를 타고 들어가봤는데
```
  export type CharacterOrderByWithRelationInput = {
    id?: SortOrder
    name?: SortOrder
    type?: SortOrder
    level?: SortOrder
    is_public?: SortOrder
    created_at?: SortOrder
    is_delete?: SortOrder
    updated_at?: SortOrder
    user_id?: SortOrder
    Activity?: ActivityOrderByRelationAggregateInput
    Block_Block_target_idToUser?: BlockOrderByRelationAggregateInput
    User?: UserOrderByWithRelationInput
    Report?: ReportOrderByRelationAggregateInput
  }

  export type ActivityOrderByRelationAggregateInput = {
    _count?: SortOrder
  }
```
Activity랑 조인해서 조회를 하는 경우에, Activity의 특정 값을 기준으로 정렬할 수 있는게 아니라 
_count 같은 Aggregate Input으로만 정렬이 가능한듯?? 
테이블을 생성할때 prisma가 자동으로 저렇게 설정해 둔 것 같아서 그걸 고치려면 좀 복잡해지는 것 같더라구.

2023-04-08 14:38 UTC, devkwonsehoon commented
오케이 우선은 클라가 기다리니 일단 sort로 정렬하고 추후에 업데이트 해봅시다.!!

2023-04-08 14:38 UTC, devkwonsehoon approved these changes

2023-04-11 03:27 UTC, merged